name: Manual AUR Publish

permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  publish:
    name: AUR Publish
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [rustmius, rustmius-bin, rustmius-git]

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Publish AUR package
        uses: KSXGitHub/github-actions-deploy-aur@v4.2.0
        with:
          pkgname: ${{ matrix.package }}
          pkgbuild: ./packages/${{ matrix.package }}/PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update ${{ matrix.package }}
          ssh_keyscan_types: rsa,ecdsa,ed25519