name: Continuous Integration

on:
  push:
    files:
      - '**/*.rs'
      - 'Cargo.toml'
      - 'Cargo.lock'

permissions:
  contents: read

jobs:
  check:
    name: Build Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-4-dev libvte-2.91-gtk4-dev libadwaita-1-dev

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Cargo Check
        run: cargo check

      - name: Cargo Build
        run: cargo build
